/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './views/root'
import { Route as itemsListItemsListRouteImport } from './views/itemsList/ItemsList'
import { Route as indexRouteImport } from './views/index'
import { Route as itemDetailItemDetailRouteImport } from './views/itemDetail/ItemDetail'
import { Route as itemUpsertItemCreateRouteImport } from './views/itemUpsert/ItemCreate'
import { Route as itemRemoveItemRemoveRouteImport } from './views/itemRemove/ItemRemove'
import { Route as itemUpsertItemEditRouteImport } from './views/itemUpsert/ItemEdit'

const itemsListItemsListRoute = itemsListItemsListRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const itemDetailItemDetailRoute = itemDetailItemDetailRouteImport.update({
  id: '/items_/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const itemUpsertItemCreateRoute = itemUpsertItemCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => itemsListItemsListRoute,
} as any)
const itemRemoveItemRemoveRoute = itemRemoveItemRemoveRouteImport.update({
  id: '/$id/remove',
  path: '/$id/remove',
  getParentRoute: () => itemsListItemsListRoute,
} as any)
const itemUpsertItemEditRoute = itemUpsertItemEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => itemsListItemsListRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/items': typeof itemsListItemsListRouteWithChildren
  '/items/create': typeof itemUpsertItemCreateRoute
  '/items/$id': typeof itemDetailItemDetailRoute
  '/items/$id/edit': typeof itemUpsertItemEditRoute
  '/items/$id/remove': typeof itemRemoveItemRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/items': typeof itemsListItemsListRouteWithChildren
  '/items/create': typeof itemUpsertItemCreateRoute
  '/items/$id': typeof itemDetailItemDetailRoute
  '/items/$id/edit': typeof itemUpsertItemEditRoute
  '/items/$id/remove': typeof itemRemoveItemRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/items': typeof itemsListItemsListRouteWithChildren
  '/items/create': typeof itemUpsertItemCreateRoute
  '/items_/$id': typeof itemDetailItemDetailRoute
  '/items/$id/edit': typeof itemUpsertItemEditRoute
  '/items/$id/remove': typeof itemRemoveItemRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/items/create'
    | '/items/$id'
    | '/items/$id/edit'
    | '/items/$id/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items'
    | '/items/create'
    | '/items/$id'
    | '/items/$id/edit'
    | '/items/$id/remove'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/items/create'
    | '/items_/$id'
    | '/items/$id/edit'
    | '/items/$id/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  itemsListItemsListRoute: typeof itemsListItemsListRouteWithChildren
  itemDetailItemDetailRoute: typeof itemDetailItemDetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof itemsListItemsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$id': {
      id: '/items_/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof itemDetailItemDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/create': {
      id: '/items/create'
      path: '/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof itemUpsertItemCreateRouteImport
      parentRoute: typeof itemsListItemsListRoute
    }
    '/items/$id/remove': {
      id: '/items/$id/remove'
      path: '/$id/remove'
      fullPath: '/items/$id/remove'
      preLoaderRoute: typeof itemRemoveItemRemoveRouteImport
      parentRoute: typeof itemsListItemsListRoute
    }
    '/items/$id/edit': {
      id: '/items/$id/edit'
      path: '/$id/edit'
      fullPath: '/items/$id/edit'
      preLoaderRoute: typeof itemUpsertItemEditRouteImport
      parentRoute: typeof itemsListItemsListRoute
    }
  }
}

interface itemsListItemsListRouteChildren {
  itemUpsertItemCreateRoute: typeof itemUpsertItemCreateRoute
  itemUpsertItemEditRoute: typeof itemUpsertItemEditRoute
  itemRemoveItemRemoveRoute: typeof itemRemoveItemRemoveRoute
}

const itemsListItemsListRouteChildren: itemsListItemsListRouteChildren = {
  itemUpsertItemCreateRoute: itemUpsertItemCreateRoute,
  itemUpsertItemEditRoute: itemUpsertItemEditRoute,
  itemRemoveItemRemoveRoute: itemRemoveItemRemoveRoute,
}

const itemsListItemsListRouteWithChildren =
  itemsListItemsListRoute._addFileChildren(itemsListItemsListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  itemsListItemsListRoute: itemsListItemsListRouteWithChildren,
  itemDetailItemDetailRoute: itemDetailItemDetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
